# Generated by Django 3.1.4 on 2021-06-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210619_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_1_count',
            new_name='optionfour_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_2_count',
            new_name='optionone_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3_count',
            new_name='optionthree_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_4_count',
            new_name='optiontwo_count',
        ),
    ]
