# Generated by Django 3.1.4 on 2021-06-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
