# Generated by Django 3.1.4 on 2021-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210620_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(max_length=25),
        ),
    ]
